server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jwang261/springcloud-config #如果是私有仓库要在下面配置username&password
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
