server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组建类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本设置为"text/plain"
          default-binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: groupA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    lease-renewal-interval-in-seconds: 15 # 设置心跳间隔
    lease-expiration-duration-in-seconds: 45 # 最大等待时长
    instance-id: receive-8003.com
    prefer-ip-address: true # 访问路径变为ip地址