server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
# Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true

#消费者要去访问的微服务名称 -> 注册进nacos的生产者
service-url:
  nacos-user-service: http://nacos-payment-provider∑
