server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh # 路由的ID，没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务路由的地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          filters:
            - AddRequestHeader=X-Request-Id, 4396 # 过滤器会在匹配请求头上加上一对请求头，名称为X-Request-Id，值为4396
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-30T21:56:17.561-04:00[America/New_York]
            # - Host=**.jjw.com,**.phe102.edu
            # - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性，且值为正整数的正则表达式
            # - Cookie=username,jjw # K,V键值对

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka
    register-with-eureka: true
    fetch-registry: true